// 按需全局引入 vant组件
import Vue from 'vue';
import {
  NavBar,
  Button,
  List,
  Cell,
  Tabbar,
  TabbarItem,
  Dialog,
  Toast,
  Row,
  Col,
  Grid,
  GridItem,
  Tab,
  Tabs,
  Icon,
  AddressEdit,
  Area,
  Popup,
  Form,
  Field,
  AddressList,
  Checkbox,
  CheckboxGroup,
  Picker,
  Image as VanImage,
  Divider,
  Search,
  DropdownMenu,
  DropdownItem,
  Switch,
  PullRefresh,
  RadioGroup,
  Radio,
  CellGroup,
  Uploader,
  SwipeCell,
  Loading,
  Collapse,
  CollapseItem,
  Step,
  Steps
} from 'vant';

Vue.use(SwipeCell);
Vue.use(Uploader);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(PullRefresh);
Vue.use(Switch);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Search);
Vue.use(Divider);
Vue.use(VanImage);
Vue.use(Picker);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(NavBar);
Vue.use(Toast);
Vue.use(Button);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(List);
Vue.use(Tabbar).use(TabbarItem);
Vue.use(Row);
Vue.use(Col);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Icon);
Vue.use(AddressEdit);
Vue.use(Area);
Vue.use(Popup);
Vue.use(Form);
Vue.use(Field);
Vue.use(AddressList);
Vue.use(Loading);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Step);
Vue.use(Steps);
Vue.use(Dialog);